version: "3.3"
services:
  db:
    container_name: db
    image: mysql:5.7.26
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
    expose:
      - "3306"