version: "3.3"
services:
  db:
    container_name: db
    image: mysql:5.7.27
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
    expose:
      - "3306"

  # todo: setup api container
  # api:
  #   container_name: api
  #   image: node:latest
  #   restart: always
  #   ports:
  #     - "8000:8000"
  #   expose:
  #     - "8000"
      
# todo: make this statement a script so the user doesn't have to call it manually
# ! potentially not needed with mysql:5.7.27
# a mysql script to make everything accessable
# ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY '{admin}';
# ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '{admin}';
# SELECT plugin FROM mysql.user WHERE User = 'root';
